// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteApi(arg1, arg2) {
  return window['go']['desktop']['Api']['DeleteApi'](arg1, arg2);
}

export function GetApi(arg1, arg2) {
  return window['go']['desktop']['Api']['GetApi'](arg1, arg2);
}

export function PostApi(arg1, arg2) {
  return window['go']['desktop']['Api']['PostApi'](arg1, arg2);
}

export function PutApi(arg1, arg2) {
  return window['go']['desktop']['Api']['PutApi'](arg1, arg2);
}
