// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function DeleteApi(arg1:string,arg2:string):Promise<desktop.ApiResp>;

export function GetApi(arg1:string,arg2:string):Promise<desktop.ApiResp>;

export function PostApi(arg1:string,arg2:string):Promise<desktop.ApiResp>;

export function PutApi(arg1:string,arg2:string):Promise<desktop.ApiResp>;
