## 以nginx为基础镜像，方便调试，或者直接使用nginx容器

version: "3"

services:
  nginx-with-ui:
    image: registry.cn-hangzhou.aliyuncs.com/tuon-pub/nginx-with-ui
    restart: always
    container_name: nginx-with-ui
    ports:
      - 38080:38080
#    network_mode: host
    volumes:
      - ./docker/data:/app/data
      - ./docker/data/conf:/app/conf
